### PR TITLE
Fix inconsistent update failures

### LINKED ISSUE #145: Update not functioning anymore
I'm using latest version of ungoogled Chromium with firejail sandbox.
Updates are announced as usual, clicking on name of extension formerly started update.
Now clicking only opens a new tab (in background). Then nothing happens until the new tab is manually closed then update seems to be downloaded into download folder. Thats it! Nothing else happens.
I can manually update the downloded extension by drag 'n drop into chrome://extensions/. 
The following is set:
> If you are using ungoogled-chromium: You must change the flag chrome://flags/#extension-mime-request-handling to Always prompt for install.
The following is unset:
> If you are NOT using ungoogled-chromium: Ensure the following option is checked: Extension Options (chrome://extensions/?options=ocaahdebbfolfmndjeplogmgcagdmblk) > Advanced > Always download CRX files

What I tried to no avail: disabled all non relevant extensions, started update by right click 'update all extensions'

noupdate

### PR DESCRIPTION
**Pull request by pdf**
Fixes #145 

Based on the suggestion from @NeverDecaf here: https://github.com/NeverDecaf/chromium-web-store/issues/145#issuecomment-1960008408

I've been using this since Feb 2024 on ungoogled-chromium.

### CODE REVIEW

**Comment by pdf** [comment]
@ylluminate some extensions require a browser restart before this extension can see the updated version.

**Comment by NeverDecaf** [comment]
Are you still able to install extensions from the chrome web store with this patched extension? This *should* completely break that functionality as the window object isn't available to service workers.

**Comment by pdf** [comment]
You're correct, add from chrome store does not work in the background process with this change.

**Comment by NeverDecaf** [comment]
Unfortunately that fix was just a quick band-aid for a specific issue; since it breaks functionality elsewhere I'm going to pursue a true fix in the linked issue instead.

**Pull request closed without merging**
